import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

/**
 * The templates dir is at packages/create-helpbase/templates/, sibling
 * to dist/ where this bundled file lives at runtime.
 *
 * Generated by `pnpm sync:templates` from apps/web/. See scripts/sync-templates.mjs
 * for what gets included and how transforms work. The generated dir is
 * committed to git so PR diffs are reviewable, and CI gates drift between
 * apps/web and templates/ via `pnpm sync:templates && git diff --exit-code`.
 */
const TEMPLATES_DIR = path.resolve(__dirname, "../templates")

/**
 * Token in templates/ files that gets replaced with the user's project name.
 * Chosen to be invalid as a TypeScript identifier so it can never appear
 * in real code by accident. Literal string replace, not regex, so project
 * names with regex metacharacters are safe.
 */
const PROJECT_NAME_TOKEN = "__HELPBASE_PROJECT_NAME__"

export interface ScaffoldOptions {
  projectName: string
  projectDir: string
}

/**
 * Scaffold a help center project by walking the templates dir and copying
 * each file to the destination, with the project name token replaced.
 *
 * Pre-flight: asserts the templates dir exists. If not, the package was
 * published incorrectly (templates missing from `files` array in
 * package.json) — fail loudly with a clear message instead of a cryptic
 * ENOENT later.
 */
export function scaffoldProject({ projectName, projectDir }: ScaffoldOptions): void {
  if (!fs.existsSync(TEMPLATES_DIR)) {
    throw new Error(
      `Templates directory not found at ${TEMPLATES_DIR}.\n` +
      `  Cause: this is likely a packaging bug — the create-helpbase package was published\n` +
      `         without the templates/ directory included.\n` +
      `  Fix:   please file an issue at https://github.com/Codehagen/helpbase/issues\n`,
    )
  }

  fs.mkdirSync(projectDir, { recursive: true })
  copyDirWithTokenReplace(TEMPLATES_DIR, projectDir, projectName)
}

/**
 * Recursively copy `src` to `dest`, replacing PROJECT_NAME_TOKEN with
 * `projectName` in text files (.ts, .tsx, .json, .mjs, .css, .mdx).
 * Binary files (favicon.ico) are copied byte-for-byte.
 */
function copyDirWithTokenReplace(src: string, dest: string, projectName: string): void {
  const entries = fs.readdirSync(src, { withFileTypes: true })
  for (const entry of entries) {
    const srcPath = path.join(src, entry.name)
    const destPath = path.join(dest, entry.name)

    if (entry.isDirectory()) {
      fs.mkdirSync(destPath, { recursive: true })
      copyDirWithTokenReplace(srcPath, destPath, projectName)
      continue
    }

    if (isTextFile(entry.name)) {
      const content = fs
        .readFileSync(srcPath, "utf-8")
        .split(PROJECT_NAME_TOKEN)
        .join(projectName)
      fs.writeFileSync(destPath, content)
    } else {
      fs.copyFileSync(srcPath, destPath)
    }
  }
}

/**
 * Wipe the sample content directories that ship with the templates.
 * Used by index.ts when AI generation succeeds — the user wants to see
 * their AI-generated articles cleanly, not mixed with sample placeholders.
 *
 * Safe to call even if the dirs don't exist (a previous wipe, a custom
 * template, etc.). Only deletes content/ subdirectories, not the content/
 * dir itself, so subsequent AI generation can still write into it.
 */
export function clearSampleContent(projectDir: string): void {
  const contentDir = path.join(projectDir, "content")
  if (!fs.existsSync(contentDir)) return
  for (const entry of fs.readdirSync(contentDir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      fs.rmSync(path.join(contentDir, entry.name), {
        recursive: true,
        force: true,
      })
    }
  }
}

const TEXT_EXTENSIONS = new Set([
  ".ts",
  ".tsx",
  ".js",
  ".jsx",
  ".json",
  ".mjs",
  ".cjs",
  ".css",
  ".mdx",
  ".md",
])

function isTextFile(filename: string): boolean {
  // Files without extensions (like .gitignore) are treated as text.
  if (filename.startsWith(".")) return true
  const ext = path.extname(filename)
  return TEXT_EXTENSIONS.has(ext)
}
