import type { CliTree } from "./tree.js"

/**
 * Emit a bash completion script.
 *
 * Install:
 *   eval "$(helpbase completion bash)"
 *
 * Or persistent:
 *   helpbase completion bash > /etc/bash_completion.d/helpbase
 *   # or ~/.local/share/bash-completion/completions/helpbase
 *
 * Strategy: single function registered with `complete -F`. Uses
 * COMP_WORDS / COMP_CWORD to locate the active subcommand and emit the
 * right flag set. Falls back to subcommand list when cursor is at
 * position 1.
 */
export function bashScript(tree: CliTree): string {
  const fn = `_${tree.name.replace(/[^a-zA-Z0-9_]/g, "_")}_completion`

  const subcommandNames = tree.subcommands.map((c) => c.name).join(" ")
  const globalFlags = tree.globalFlags.map((f) => f.flag).join(" ")

  const cases = tree.subcommands
    .map((cmd) => {
      const flags = [...cmd.flags.map((f) => f.flag), ...tree.globalFlags.map((f) => f.flag)]
        .filter((f, i, arr) => arr.indexOf(f) === i)
        .join(" ")
      return `    ${cmd.name})\n      COMPREPLY=( $(compgen -W "${flags}" -- "$cur") )\n      return 0\n      ;;`
    })
    .join("\n")

  return `# bash completion for ${tree.name}
# Generated by '${tree.name} completion bash'

${fn}() {
  local cur prev words cword
  cur="\${COMP_WORDS[COMP_CWORD]}"

  # Find the subcommand (first non-flag word after the program name).
  local cmd=""
  local i
  for ((i=1; i < COMP_CWORD; i++)); do
    local w="\${COMP_WORDS[i]}"
    case "$w" in
      -*) continue ;;
      *) cmd="$w"; break ;;
    esac
  done

  if [[ -z "$cmd" ]]; then
    COMPREPLY=( $(compgen -W "${subcommandNames} ${globalFlags}" -- "$cur") )
    return 0
  fi

  case "$cmd" in
${cases}
    *)
      COMPREPLY=( $(compgen -W "${globalFlags}" -- "$cur") )
      return 0
      ;;
  esac
}

complete -F ${fn} ${tree.name}
`
}
