import type { CliTree } from "./tree.js"

/**
 * Emit a fish completion script.
 *
 * Install:
 *   helpbase completion fish > ~/.config/fish/completions/helpbase.fish
 *   # reload your shell or run `source` on the file
 *
 * Or for the current session:
 *   helpbase completion fish | source
 *
 * Strategy: one `complete` declaration per subcommand + per-flag. fish
 * handles per-subcommand flag scoping natively with `-n '__fish_seen_subcommand_from <cmd>'`,
 * which is the cleanest of the four shells for this shape.
 */
export function fishScript(tree: CliTree): string {
  const lines: string[] = [
    `# fish completion for ${tree.name}`,
    `# Generated by '${tree.name} completion fish'`,
    "",
    // Disable file completion by default; flags/subcommands only.
    `complete -c ${tree.name} -f`,
    "",
    "# Subcommands",
  ]

  for (const cmd of tree.subcommands) {
    lines.push(
      `complete -c ${tree.name} -n '__fish_use_subcommand' -a '${cmd.name}' -d ${quote(cmd.description)}`,
    )
  }

  // Global flags available everywhere.
  lines.push("", "# Global flags")
  for (const f of tree.globalFlags) {
    const long = f.flag.replace(/^--/, "")
    lines.push(
      `complete -c ${tree.name} -l ${long} -d ${quote(f.description)}`,
    )
  }

  // Per-subcommand flags, scoped with __fish_seen_subcommand_from.
  lines.push("", "# Subcommand flags")
  for (const cmd of tree.subcommands) {
    for (const f of cmd.flags) {
      // --help is global via Commander; skip here to avoid duplicate entries.
      if (f.flag === "--help") continue
      const long = f.flag.replace(/^--/, "")
      lines.push(
        `complete -c ${tree.name} -n '__fish_seen_subcommand_from ${cmd.name}' -l ${long} -d ${quote(f.description)}`,
      )
    }
  }

  return lines.join("\n") + "\n"
}

/** Single-quote a string for fish. Fish does not interpret escapes inside
 *  single quotes, so we only need to handle single quotes themselves. */
function quote(s: string): string {
  return `'${s.replace(/\\/g, "\\\\").replace(/'/g, "\\'")}'`
}
