import type { CliTree } from "./tree.js"

/**
 * Emit a PowerShell completion script.
 *
 * Install (current session):
 *   helpbase completion powershell | Out-String | Invoke-Expression
 *
 * Persistent: add the same line to your `$PROFILE`.
 *
 * Strategy: Register-ArgumentCompleter with -Native. We inspect the AST
 * to figure out whether the cursor is on the subcommand slot or inside
 * a subcommand, and emit CompletionResult objects with tooltips. Keeps
 * the Windows experience first-class instead of the usual "oh right,
 * PowerShell is a thing" afterthought.
 */
export function powershellScript(tree: CliTree): string {
  // Build a nested hashtable literal of subcommand → flags[] so the
  // script can look it up without re-parsing at completion time.
  const flagMap = tree.subcommands
    .map((cmd) => {
      const flagLines = cmd.flags
        .map(
          (f) => `    @{ Name = '${f.flag}'; Tooltip = ${psString(f.description)} }`,
        )
        .join("`n")
      return `  '${cmd.name}' = @(
${flagLines}
  )`
    })
    .join("`n")

  const subcmdEntries = tree.subcommands
    .map(
      (c) =>
        `    @{ Name = '${c.name}'; Tooltip = ${psString(c.description)} }`,
    )
    .join("`n")

  const globalFlags = tree.globalFlags
    .map(
      (f) => `  @{ Name = '${f.flag}'; Tooltip = ${psString(f.description)} }`,
    )
    .join("`n")

  return `# PowerShell completion for ${tree.name}
# Generated by '${tree.name} completion powershell'

Register-ArgumentCompleter -Native -CommandName ${tree.name} -ScriptBlock {
  param($wordToComplete, $commandAst, $cursorPosition)

  $subcommands = @(
${subcmdEntries}
  )

  $globalFlags = @(
${globalFlags}
  )

  $commandFlags = @{
${flagMap}
  }

  # Walk the AST to find whether a subcommand has been typed.
  $sub = $null
  foreach ($el in $commandAst.CommandElements | Select-Object -Skip 1) {
    $v = $el.Value
    if ($null -ne $v -and -not $v.StartsWith('-')) {
      $sub = $v
      break
    }
  }

  if ($null -eq $sub -or $sub -eq $wordToComplete) {
    $results = $subcommands + $globalFlags
  } elseif ($commandFlags.ContainsKey($sub)) {
    $results = $commandFlags[$sub] + $globalFlags
  } else {
    $results = $globalFlags
  }

  $results |
    Where-Object { $_.Name -like "$wordToComplete*" } |
    ForEach-Object {
      [System.Management.Automation.CompletionResult]::new(
        $_.Name, $_.Name, 'ParameterValue', $_.Tooltip
      )
    }
}
`
}

/** Quote a string as a single-quoted PowerShell literal. Inside '...',
 *  a single quote is escaped by doubling it. */
function psString(s: string): string {
  return `'${s.replace(/'/g, "''")}'`
}
