import type { CliTree } from "./tree.js"

/**
 * Emit a zsh completion script using _describe + _arguments.
 *
 * Install:
 *   eval "$(helpbase completion zsh)"
 *
 * Or persistent (preferred):
 *   mkdir -p ~/.zsh/completions
 *   helpbase completion zsh > ~/.zsh/completions/_helpbase
 *   # then in ~/.zshrc: fpath=(~/.zsh/completions $fpath); compinit
 *
 * Strategy: a compdef function that branches on CURRENT. When completing
 * the subcommand slot we use _describe; inside a subcommand we enumerate
 * flags. Unlike bash we can attach per-flag descriptions, which is the
 * whole reason people love zsh completion.
 */
export function zshScript(tree: CliTree): string {
  const fn = `_${tree.name.replace(/[^a-zA-Z0-9_]/g, "_")}`

  const subcmdDescriptions = tree.subcommands
    .map((c) => `    '${c.name}:${escapeZsh(c.description)}'`)
    .join("\n")

  const globalFlagArgs = tree.globalFlags
    .map((f) => `'${f.flag}[${escapeZsh(f.description)}]'`)
    .join(" \\\n        ")

  const cases = tree.subcommands
    .map((cmd) => {
      const flagArgs = cmd.flags
        .map((f) => `'${f.flag}[${escapeZsh(f.description)}]'`)
        .join(" \\\n            ")
      return `    ${cmd.name})
      _arguments \\
            ${flagArgs || "':: :->noop'"}
      ;;`
    })
    .join("\n")

  return `#compdef ${tree.name}
# zsh completion for ${tree.name}
# Generated by '${tree.name} completion zsh'

${fn}() {
  local -a subcmds
  subcmds=(
${subcmdDescriptions}
  )

  local context state line
  _arguments -C \\
        ${globalFlagArgs || "':: :->noop'"} \\
        '1: :->subcmd' \\
        '*:: :->args'

  case $state in
    subcmd)
      _describe -t commands '${tree.name} command' subcmds
      ;;
    args)
      case $line[1] in
${cases}
      esac
      ;;
  esac
}

${fn} "$@"
`
}

/**
 * Escape characters that break zsh _describe / _arguments syntax.
 * Single quotes, colons, and brackets need special care because they're
 * structural delimiters. We do not try to preserve every unicode glyph;
 * descriptions are best-effort and flagged at test time.
 */
function escapeZsh(s: string): string {
  return s
    .replace(/'/g, "'\\''")
    .replace(/:/g, "\\:")
    .replace(/\[/g, "\\[")
    .replace(/\]/g, "\\]")
}
